config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  #get 'recipes', to: 'recipes#index'
  #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post 'recipes', to: 'recipes#create'
  #get 'recipes/:id/edit', to: 'reciptes#edit', as: 'edit_recipe'
  #patch 'recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete 'recipes/:id', to: 'recipes#destroy'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :users, except: [:new, :destroy]
  
  get '/register', to: 'users#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :user_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  
  private
  
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5Mb")
      end  
    end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end
  
  def show
    
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully"
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
  
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe has been deleted successfully"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], user: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  
  private
  
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
    end  
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def require_same_user
      if current_user != @recipe.user and !current_user.admin?
        flash[:danger] = "You can only edit your own recipe"
        redirect_to recipes_path
      end
    end
    
    def require_user_like
      if !logged_in?
        flash[:danger] = "You must log in to perform that action"
        redirect_to :back
      end
    end
  
    def admin_user
      redirect_to recipes_path unless current_user.admin?
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
  
      <strong>Styles:</strong>
      <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
      <br><br>
      
      <strong>Ingredients:</strong>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
        <% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
      <% end %>
      <br><br>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5Mb');  
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", users_path %>
  </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info center">
        <%= link_to gravatar_for(recipe.user, size: 100), user_path(recipe.user) %>
        <h5>Chef name: <%= recipe.user.username %></h5>
      </section>
    </div>
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <% if recipe.styles.any? %>
        <p>Styles: <%= render recipe.styles %></p>
      <% end %>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, height: "150", class: "gravatar") if recipe.picture? %>
    </div>
  </div>
  <hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.user, size: 200), user_path(@recipe.user) %>
    <p>
      <h5>Brought to you by: <%= @recipe.user.username %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? and @recipe.user == current_user || current_user.admin? %>
      <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>
    <% if logged_in? and current_user.admin? %>
      <%= link_to "[Delete Recipe]", @recipe, method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    <div class="well">
      <% if @recipe.styles.any? %>
        <p><strong>Styles: </strong><%= render @recipe.styles %></p>
      <% end %>
      <% if @recipe.ingredients.any? %>
        <p><strong>Ingredients: </strong><%= render @recipe.ingredients %></p>
      <% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %></h5>