config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  #get 'recipes', to: 'recipes#index'
  #get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post 'recipes', to: 'recipes#create'
  #get 'recipes/:id/edit', to: 'reciptes#edit', as: 'edit_recipe'
  #patch 'recipes/:id', to: 'recipes#update'
  #get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete 'recipes/:id', to: 'recipes#destroy'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :users, except: [:new, :destroy]
  
  get '/register', to: 'users#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to ICMJ Recipes</h1>
  
  <h2>This is the home for cooking lovers</h2>
  
  <%= link_to "Sign up now", register_path, class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">
      Browse and view recipes as a guest and Sign up later
    </h2>
    <p><%= link_to "Browse recipes listing", recipes_path, class: "btn btn-small btn-warning" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">
      Add/update your recipes/create reviews/like-dislike recipes and much more...
    </h2>
    <p><%= link_to "Log in to your account", login_path, class: "btn btn-small btn-warning" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">
      Browse and view recipes as a guest and Sign up later
    </h2>
    <p><%= link_to "Browse recipes listing", "", class: "btn btn-small btn-warning" %></p>
  </div>
</div>